### ISSUE TITLE
difference with protobufjs pbts

### ISSUE THREAD

**Issue by adematte** [anfema/grpc-code-generator#2]
I am working on a similar project to provide better typescript definitions and generated code for projects using the node grpc package (which is using protobufjs). And such, I am investigating this package to see if it would be worthwhile to contribute to it directly instead of creating another.

Can you share some insight on how different this will be from protobufjs typescript definitions ? https://github.com/dcodeIO/ProtoBuf.js/#pbts-for-typescript

Also, I like the "template" idea but wouldn't it be more practical to actually use a real template engine to generate the code? something like handlebars, mustache, ejs ...

**Comment by andrew8er** [comment]
The differences to `pbts` are:
- The last time I checked, `pbts` did not generate types for gRPC services.
- I wanted to have the option to generate definitions for wrappers around the service implementations and clients (I currently have an internal middleware stack based on [@thi.ng/rstream](https://www.npmjs.com/package/@thi.ng/rstream)).

Yes, a real template engine would be more practical. Until now, this project is just a quick hack, but I am open to suggestions.
