### ISSUE TITLE
generate the response class instead of interface ?

### ISSUE THREAD

**Issue by fatfatson** [anfema/grpc-code-generator#3]
because we can not `new` an interface, 
so when writing the response object,
we can only use a literal object without any typing tips.
though the `callback` call will verify its arguments,
but I also hope getting more tips when defining the object.

![image](https://user-images.githubusercontent.com/5842874/58742976-37d3dd00-845c-11e9-92bb-0e01650cb5f9.png)

**Comment by andrew8er** [comment]
Actually, I have full typing tips in VS Code. Which `Service` interface did you use, the one generated in `grpc-node.d.ts`?

**Comment by andrew8er** [comment]
Ah now I see, it's pretty simple. You define an arbitrary object without any type information in with `let` and the use that object:
```ts
let ret = {
  // ...
}

callback(null, ret);
```
Typescript has no way of knowing, that this object must conform to the response type in the declaration. It will rather create an adhoc type for this object.

In fact, why do you even create an intermediate variable? You could just use this:

```ts
callback(null, {
  // ..
});
```

If you really have to use an intermediate variable, you have to specify the type like this:

```ts
// Also please use const!
const ret: ResponseType = {
  // Enjoy full type hints here...
}

callback(null, ret);
```

**Comment by fatfatson** [comment]
thanks @andrew8er ,
now i'm using the class generated by protobuf.js,
i'd like to operate a typed-object ~

**Comment by andrew8er** [comment]
Is your issue answered then?
